-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 21:38:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `email` VARCHAR(200) NULL,
  `contraseña` VARCHAR(255) NULL,
  `fecha_creacion` DATE NULL,
  `fecha_modificacion` DATE NULL,
  `id_usuario_creacion` INT NULL,
  `id_usuario_modificacion` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`remitentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`remitentes` (
  `id` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nombre_remitente` VARCHAR(255) NULL,
  `correo_remitente` VARCHAR(200) NULL,
  `remitentescol` VARCHAR(45) NULL,
  `estado` INT NULL,
  `fecha_creacion` DATE NULL,
  `fecha_modificacion` DATE NULL,
  `id_usuario_creacion` INT NULL,
  `id_usuario_modifica` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_remitentes_usuarios_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_remitentes_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuracion_correos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuracion_correos` (
  `id` INT NOT NULL,
  `id_remitente` INT NOT NULL,
  `estado` INT NULL,
  `proveedor` VARCHAR(100) NULL,
  `servidor_smtp` VARCHAR(150) NULL,
  `puerto` INT NULL,
  `usuarios_smtp` VARCHAR(150) NULL,
  `clave_smtp` VARCHAR(255) NULL,
  `usa_tls` INT NULL,
  `usa_ssl` INT NULL,
  `fecha_creacion` DATE NULL,
  `fecha_modificacion` DATE NULL,
  `id_usuario_creacion` INT NULL,
  `id_usuario_modificacion` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_configuracion_correos_remitentes1_idx` (`id_remitente` ASC) VISIBLE,
  CONSTRAINT `fk_configuracion_correos_remitentes1`
    FOREIGN KEY (`id_remitente`)
    REFERENCES `mydb`.`remitentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
